# Generated by Django 5.0.6 on 2024-08-03 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('labtech_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=255)),
                ('profile_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_technicians', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
