# Generated by Django 5.0.6 on 2024-08-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testname_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='normal_range',
        ),
    ]
