# Generated by Django 5.0.6 on 2024-08-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_tests_normal_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('testtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('tests_names', models.CharField(max_length=300)),
                ('normal_range', models.CharField(max_length=100)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tests')),
            ],
        ),
    ]
