# Generated by Django 5.0.6 on 2024-09-03 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_labtechnician_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnicianSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booking')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.labtechnician')),
            ],
        ),
    ]
