# Generated by Django 5.0.6 on 2024-09-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labtechnicianschedule',
            unique_together={('technician', 'booking')},
        ),
    ]
