# Generated by Django 5.0.6 on 2025-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_homecollection_booking_home_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('collected', 'Collected'), ('test done', 'Test Done')], default='pending', max_length=20),
        ),
    ]
