# Generated by Django 5.0.6 on 2024-08-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_labtechnician'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestName',
            fields=[
                ('name_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=50)),
                ('lad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_type_names', models.CharField(max_length=300)),
                ('normal_range', models.CharField(max_length=255)),
                ('name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.testname')),
            ],
        ),
    ]
