# Generated by Django 5.0.6 on 2024-08-18 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='test_types',
            field=models.ManyToManyField(to='myapp.testtype'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.testname'),
        ),
    ]
