# Generated by Django 5.0.6 on 2024-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_booking_test_types_booking_testtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='testtype',
        ),
        migrations.AddField(
            model_name='booking',
            name='test_types',
            field=models.ManyToManyField(to='myapp.testtype'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
