# Generated by Django 5.0.6 on 2024-08-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_booking_testtype_booking_test_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='test_types',
            field=models.ManyToManyField(related_name='bookings', to='myapp.testtype'),
        ),
    ]
