# Generated by Django 5.0.6 on 2024-08-25 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_booking_test_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('amount_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.testtype')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.amount')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booking')),
            ],
        ),
    ]
