# Generated by Django 5.0.6 on 2024-08-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_amount_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechnician',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
