# Generated by Django 5.0.6 on 2024-09-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_labtechnicianschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtechnicianschedule',
            name='id',
        ),
        migrations.AddField(
            model_name='labtechnicianschedule',
            name='schedule_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
