# Generated by Django 5.0.6 on 2024-09-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_collectionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.collectionstatus')),
            ],
        ),
        migrations.CreateModel(
            name='TestValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(max_length=255)),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='myapp.testresult')),
            ],
        ),
    ]
