# Generated by Django 5.0.6 on 2024-09-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_testresult_testvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.testtype'),
            preserve_default=False,
        ),
    ]
