# Generated by Django 5.0.6 on 2024-09-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_testresult_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_types',
            field=models.ManyToManyField(related_name='test_results', to='myapp.testtype'),
        ),
    ]
