# Generated by Django 5.0.6 on 2025-01-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_testresult_test_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/'),
        ),
    ]
